<?php

namespace lnl\lnlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ItemRelationshipsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRelationshipsRepository extends EntityRepository
{

}
