<?php

namespace lnl\lnlBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MetaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MetaRepository extends EntityRepository
{

}
