imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: "%debug_toolbar%"
    intercept_redirects: "%debug_redirects%"

bazinga_faker:
    orm: doctrine
    entities:
            lnl\lnlBundle\Entity\Items:
                number: 5
                custom_formatters:
                                slug:   { method: word }
                                title:   { method: word }
                                status: { method: numberBetween, parameters: [ "0", "1" ] }
            lnl\lnlBundle\Entity\Categories:
                number: 5
                custom_formatters:
                                slug:   { method: word }
                                title:   { method: word }
                                image: { method: image, parameters: [ "/tmp", "640","640" ] }
            lnl\lnlBundle\Entity\ItemRelationships:
                number: 5
            lnl\lnlBundle\Entity\Meta:
                number: 5
                custom_formatters:
                                itemKey: { method: randomElement, parameters: [ ["meta_description", "meta_keywords", "something_else"] ] }
                                itemValue:   { method: word }
                                itemType: { method: randomElement, parameters: [ ["page", "other"] ] }
            lnl\lnlBundle\Entity\Ratings:
                            number: 5



monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration
        #firephp:
        #    type:   firephp
        #    level:  info
        #chromephp:
        #    type:   chromephp
        #    level:  info

assetic:
    use_controller: "%use_assetic_controller%"

#swiftmailer:
#    delivery_address: me@example.com
