admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin

sonata_user_security:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"

sonata_user_resetting:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
    prefix: /resetting

sonata_user_profile:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
    prefix: /profile

sonata_user_register:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
    prefix: /register

sonata_user_change_password:
    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
    prefix: /profile

_welcome:
    path:     /
    defaults: { _controller: lnlBundle:Home:index }

_items:
        path:     /item/{item}
        defaults: { _controller: lnlBundle:Items:show }

_categories:
        path:     /categories/
        defaults: { _controller: lnlBundle:Categories:create }

_category:
        path:     /{category}/
        defaults: { _controller: lnlBundle:Categories:show }

_subcategory:
        path:     /{category}/{subcategory}/
        defaults: { _controller: lnlBundle:Categories:show }

