lnl\lnlBundle\Entity\Categories:
  type: entity
  repositoryClass: lnl\lnlBundle\Entity\CategoriesRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    title:
      type: text
      nullable: true
    slug:
      type: string
      length: 255
      nullable: true
    image:
      type: text
      nullable: true
  oneToMany:
    children:
      targetEntity: lnl\lnlBundle\Entity\Categories
      mappedBy: parent
    itemRelationships:
      targetEntity: lnl\lnlBundle\Entity\ItemRelationships
      mappedBy: categories
  manyToOne:
    parent:
      targetEntity: lnl\lnlBundle\Entity\Categories
      inversedBy: children
      joinColumns:
        parent_id:
          referencedColumnName: id
