lnl\lnlBundle\Entity\Items:
  type: entity
  repositoryClass: lnl\lnlBundle\Entity\ItemsRepository
  fields:
    id:
      id: true
      type: integer
      generator:
        strategy: AUTO
    title:
      type: text
      nullable: true
    slug:
      type: text
      nullable: true
    content:
      type: text
      nullable: true
    status:
      type: integer
      nullable: true
  oneToMany:
    itemRelationships:
      targetEntity: lnl\lnlBundle\Entity\ItemRelationships
      mappedBy: items
    meta:
      targetEntity: lnl\lnlBundle\Entity\Meta
      mappedBy: items
    ratings:
      targetEntity: lnl\lnlBundle\Entity\Ratings
      mappedBy: items
